### ISSUE TITLE
Is it possible to make a better controller ?

### ISSUE THREAD

**Issue by Napolitain** [Cyr-ius/hass-heatzy#20]
Currently, my controller looks like that :

![image](https://user-images.githubusercontent.com/18146363/161448671-fdb96bae-4c92-4f72-a3f5-d77195ff8b01.png)

Note that there is no distinct way to
- see current
- change current

At this time of the screenshot, I was on "programmed - nightmode".

I understand the difficulties are elsewhere (API) but I think we need a much better controller !

**Comment by Napolitain** [comment]
Okay looking at it, it just seems it is a HA native UI which is just quite bad. I'll search for better ones I guess.

**Comment by Cyr-ius** [comment]
Heatzy convectors do not have a temperature sensor. It is therefore necessary to make a generic Thermostat and to associate a temperature sensor and the Heatzy switch in configuration.yaml

```
climate:
  - platform: generic_thermostat
    name: Thermostat Salon
    heater: climate.salon #Heatzy climate sensor
    target_sensor: sensor.lumi_rdc_temperature #Your temperature sensor (for me , it's Xiaomi Aqara Lumi)
    away_temp: 14
    comfort_temp: 19.5
    sleep_temp: 17.5
    hot_tolerance: 0.2
    cold_tolerance: 0.2
    keep_alive:
      minutes: 5
```
